```{r coxtab, cache=TRUE}
survfunc <- function(time, event, eventname) {
  levsef <- levels(pdata$shf_ef_cat)

  out <- data.frame(matrix(NA, ncol = 10, nrow = 4))

  out[1, 1] <- eventname

  colnames(out) <- c(
    "",
    paste(rep(levsef, each = 3), rep(c(levels(pdata$ht)), 3))
  )

  ## incidence rate
  out[2, 1] <- ".  Incidence*"

  for (i in seq_along(levsef)) {
    survdata2 <- pdata %>%
      mutate(eventcount = if_else(!!sym(event) == "Yes", 1, 0)) %>%
      filter(shf_ef_cat == levsef[i])

    ev <- by(survdata2[, "eventcount"], survdata2[, "ht"], sum)
    s <- by(survdata2[, time], survdata2[, "ht"], sum) / 365.25
    r <- pois.exact(x = ev, pt = s / 1000)

    out[2, (2 + (i - 1) * 3):(4 + (i - 1) * 3)] <- paste0(
      ev, ", ",
      dF(s, dig = 0), ", ",
      dF(r$rate, dig = 0), " (",
      dF(r$lower, dig = 0), "-",
      dF(r$upper, dig = 0), ")"
    )

    # cox regressions
    ## crude
    mod <- coxph(formula(paste0(
      "Surv(", time, ",", event, "=='Yes') ~ ht"
    )),
    data = pdata %>% filter(shf_ef_cat == levsef[i])
    )
    smod <- summary(mod)
    out[3, 1] <- ".  Crude HR (95% CI), p"
    out[3, (2 + (i - 1) * 3):(4 + (i - 1) * 3)] <- c(
      "reference", paste0(
        dF(smod$conf.int[1:2, 1], dig = 2),
        " (", dF(smod$conf.int[1:2, 3], dig = 2),
        "-", dF(smod$conf.int[1:2, 4], dig = 2), "), ",
        dF(smod$coef[1:2, 5], dig = 3, p = TRUE)
      )
    )

    # out[3, (5 + (i - 1) * 4)] <- last(dF(car::Anova(mod, type = 3, test.statistic = "Wald")$`Pr(>Chisq)`, dig = 3, p = T))

    ## adj comorbs
    amod <- hf_coxph_mids(formula(paste0(
      "Surv(", time, ",", event, "=='Yes') ~ ht +",
      paste(modvars$var, collapse = " + ")
    )),
    data = imp, subset = quote(shf_ef_cat == levsef[i])
    )

    ## df the number of events minus the regression coefficients.
    ## There is support for this from middle of page 149 of the book by Parmer & Machin (ISBN 0471936405)
    asmod <- summary(pool(amod,
      dfcom =
        (amod$analyses[[1]]$nevent - length(amod$analyses[[1]]$coefficients))
    ))

    out[4, 1] <- ".  Adj HR (95% CI), p-value"
    out[4, (2 + (i - 1) * 3):(4 + (i - 1) * 3)] <- c(
      "reference",
      paste0(
        dF(exp(asmod$estimate[1:2]), dig = 2),
        " (", dF(exp(asmod$estimate[1:2] - global_z05 * asmod$std.error[1:2]), dig = 2),
        "-", dF(exp(asmod$estimate[1:2] + global_z05 * asmod$std.error[1:2]), dig = 2), "), ",
        dF(asmod$p.value[1:2], dig = 3, p = TRUE)
      )
    )
  }
  return(out)
}
```

```{r coxtabout, cache=cacheon, dependson="coxtab"}
coxcvdhfh <- survfunc(
  time = "sos_outtime_hosphf",
  event = "sos_out_deathcvhosphf",
  eventname = "First HF hospitalization/CV Death (%)"
)

coxhfh <- survfunc(
  "sos_outtime_hosphf",
  "sos_out_hosphf",
  "First HF hospitalization (%)"
)

coxcvd <- survfunc(
  "sos_outtime_death",
  "sos_out_deathcv",
  "CV Death (%)"
)

coxdeath <- survfunc(
  "sos_outtime_death",
  "sos_out_death",
  "Death (%)"
)

coxall <- bind_rows(coxcvdhfh, coxhfh, coxcvd, coxdeath)

write.xlsx(coxall, paste0("./output/tabs/coxtab_", Sys.Date(), ".xlsx"), rowNames = FALSE)

colnames(coxall) <- c("", rep(c(levels(pdata$ht)), 3))
myHeader <- c(" " = 1, "HFrEF" = 3, "HFmrEF" = 3, "HFpEF" = 3)
names(myHeader) <- c(" ", "HFrEF", "HFmrEF", "HFpEF")

footnote(mykable(coxall,
  fontsize = 10,
  caption = paste0("Associations between outcomes and HT by EF")
) %>%
  landscape() %>%
  add_header_above(myHeader),
symbol = c(
  "Incidence = no events, sum py, rate/1000py (95% CI)."
)
)
```

```{r forest, fig.cap="Forest Adjusted HR First HF hospitalization or CV death", cache=cacheon}

levsef <- levels(pdata$shf_ef_cat)

out <- data.frame(matrix(NA, ncol = 7, nrow = 12))

colnames(out) <- c("ef", "ht", "loghr", "lci", "uci", "p", "hrci")

for (i in seq_along(levsef)) {
  out[1 + 4 * (i - 1), 1] <- levsef[i]
  out[(2 + 4 * (i - 1)):(4 + 4 * (i - 1)), 2] <- c("Normal BP", "Non-TRH", "aTRH")

  ## adj comorbs
  amod <- hf_coxph_mids(formula(paste0(
    "Surv(sos_outtime_hosphf, sos_out_deathcvhosphf=='Yes') ~ ht +",
    paste(modvars$var, collapse = " + ")
  )),
  data = imp, subset = quote(shf_ef_cat == levsef[i])
  )

  ## df the number of events minus the regression coefficients.
  ## There is support for this from middle of page 149 of the book by Parmer & Machin (ISBN 0471936405)
  asmod <- summary(pool(amod,
    dfcom =
      (amod$analyses[[1]]$nevent - length(amod$analyses[[1]]$coefficients))
  ))


  out[(2 + 4 * (i - 1)):(4 + 4 * (i - 1)), 3] <- c(1, asmod$estimate[1:2])
  out[(3 + 4 * (i - 1)):(4 + 4 * (i - 1)), 4] <- asmod$estimate[1:2] - global_z05 * asmod$std.error[1:2]
  out[(3 + 4 * (i - 1)):(4 + 4 * (i - 1)), 5] <- asmod$estimate[1:2] + global_z05 * asmod$std.error[1:2]
  out[(3 + 4 * (i - 1)):(4 + 4 * (i - 1)), 6] <- dF(asmod$p.value[1:2], dig = 3, p = TRUE)

  out[(2 + 4 * (i - 1)):(4 + 4 * (i - 1)), 7] <- c(
    "reference",
    paste0(
      dF(exp(asmod$estimate[1:2]), dig = 2),
      " (", dF(exp(asmod$estimate[1:2] - global_z05 * asmod$std.error[1:2]), dig = 2),
      "-", dF(exp(asmod$estimate[1:2] + global_z05 * asmod$std.error[1:2]), dig = 2), ")"
    )
  )
}

out <- out %>%
  arrange(n():1)

# exp(min(as.numeric(out$lci), na.rm=T))
# exp(max(as.numeric(out$uci), na.rm=T))

cextext <- 1

# c(bottom, left, top, right)
par(mar = c(2, 14.5, 0, 0) + 0.2)
plot(out$loghr, 1:nrow(out),
  xlab = "",
  xlim = c(
    log(0.7),
    log(1.1)
  ),
  ylim = c(1, nrow(out) + 1),
  axes = FALSE,
  ylab = NA,
  cex.lab = 1,
  main = NA,
  cex = 2,
  type = "p",
  pch = 22,
  bg = global_kicols[1],
  col = global_kicols[1]
)


for (i in 1:nrow(out)) {
  if (!is.na(out$lci[i])) {
    matplot(c(out$lci[i], out$uci[i]), c(i, i),
      type = "l", add = TRUE, col = global_kicols[1], lwd = 2
    )
  }
}

matplot(c(0, 0), c(-1, nrow(out) + 0.5), type = "l", lty = 3, add = TRUE, col = "black")

axis(1,
  cex.axis = cextext, at = log(seq(0.7, 1.1, 0.1)),
  labels = seq(0.7, 1.1, 0.1)
)

axis(2,
  at = 1:(nrow(out)),
  labels = out$ef,
  cex.axis = cextext, tick = FALSE, las = 2, line = 13.5, hadj = 0
)


axis(2,
  at = 1:(nrow(out)),
  labels = out$ht,
  cex.axis = cextext, tick = FALSE, las = 2, line = 13, hadj = 0
)

axis(2,
  at = 1:(nrow(out) + 1),
  labels = c(out$hrci, "HR (95% CI)"),
  cex.axis = cextext, tick = FALSE, las = 2, line = 5, hadj = 0.5
)

axis(2,
  at = 1:(nrow(out) + 1),
  labels = c(out$p, "P-value"),
  cex.axis = cextext, tick = FALSE, las = 2, line = 0.3, hadj = 0.5
)
```
