```{r coxtabsens, cache=TRUE}
survfunc <- function(time, event, eventname) {
  levsef <- levels(pdata$shf_ef_cat)

  out <- data.frame(matrix(NA, ncol = 11, nrow = 4))

  out[1, 1] <- eventname

  colnames(out) <- c(
    "",
    paste(rep(levsef, each = 3), rep(c(levels(pdata$htsens)), 3)), "p-value interaction"
  )

  ## incidence rate
  out[2, 1] <- ".  Incidence*"

  for (i in seq_along(levsef)) {
    survdata2 <- pdata %>%
      mutate(eventcount = if_else(!!sym(event) == "Yes", 1, 0)) %>%
      filter(shf_ef_cat == levsef[i])

    ev <- by(survdata2[, "eventcount"], survdata2[, "htsens"], sum)
    s <- by(survdata2[, time], survdata2[, "htsens"], sum) / 365.25
    r <- pois.exact(x = ev, pt = s / 1000)

    out[2, (2 + (i - 1) * 3):(4 + (i - 1) * 3)] <- paste0(
      ev, ", ",
      dF(s, dig = 0), ", ",
      dF(r$rate, dig = 0), " (",
      dF(r$lower, dig = 0), "-",
      dF(r$upper, dig = 0), ")"
    )

    # cox regressions
    ## crude
    mod <- coxph(formula(paste0(
      "Surv(", time, ",", event, "=='Yes') ~ htsens * relevel(shf_ef_cat, ref = '", levsef[i], "')"
    )),
    data = pdata
    )
    smod <- summary(mod)
    out[3, 1] <- ".  Crude HR (95% CI), p"
    out[3, (2 + (i - 1) * 3):(4 + (i - 1) * 3)] <- c(
      "reference", paste0(
        dF(smod$conf.int[1:2, 1], dig = 2),
        " (", dF(smod$conf.int[1:2, 3], dig = 2),
        "-", dF(smod$conf.int[1:2, 4], dig = 2), "), ",
        dF(smod$coef[1:2, 5], dig = 3, p = TRUE)
      )
    )

    if (i == 1) out[3, 11] <- last(dF(car::Anova(mod, type = 3, test.statistic = "Wald")$`Pr(>Chisq)`, dig = 3, p = T))

    ## adj comorbs
    amod <- with(impsens, coxph(formula(paste0(
      "Surv(", time, ",", event, " == 'Yes') ~ htsens * relevel(shf_ef_cat, ref = '", levsef[i], "') + ",
      paste(modvars$var, collapse = " + ")
    ))))

    ## df the number of events minus the regression coefficients.
    ## There is support for this from middle of page 149 of the book by Parmer & Machin (ISBN 0471936405)
    asmod <- summary(pool(amod,
      dfcom =
        (amod$analyses[[1]]$nevent - length(amod$analyses[[1]]$coefficients))
    ))

    out[4, 1] <- ".  Adj HR (95% CI), p-value"
    out[4, (2 + (i - 1) * 3):(4 + (i - 1) * 3)] <- c(
      "reference",
      paste0(
        dF(exp(asmod$estimate[1:2]), dig = 2),
        " (", dF(exp(asmod$estimate[1:2] - global_z05 * asmod$std.error[1:2]), dig = 2),
        "-", dF(exp(asmod$estimate[1:2] + global_z05 * asmod$std.error[1:2]), dig = 2), "), ",
        dF(asmod$p.value[1:2], dig = 3, p = TRUE)
      )
    )

    if (i == 1) {
      amodnoint <- with(impsens, coxph(formula(paste0(
        "Surv(", time, ",", event, " == 'Yes') ~ htsens + relevel(shf_ef_cat, ref = '", levsef[i], "') + ",
        paste(modvars$var, collapse = " + ")
      ))))

      int <- D1(amod, amodnoint)

      out[4, 11] <- dF(int$result[4], dig = 3, p = TRUE)
    }
  }
  return(out)
}
```

```{r coxtaboutsens, cache=cacheon, dependson="coxtabsens"}
coxcvdhfh <- survfunc(
  time = "sos_outtime_hosphf",
  event = "sos_out_deathcvhosphf",
  eventname = "First HF hospitalization/CV Death (%)"
)

coxhfh <- survfunc(
  "sos_outtime_hosphf",
  "sos_out_hosphf",
  "First HF hospitalization (%)"
)

coxcvd <- survfunc(
  "sos_outtime_death",
  "sos_out_deathcv",
  "CV Death (%)"
)

coxdeath <- survfunc(
  "sos_outtime_death",
  "sos_out_death",
  "Death (%)"
)

coxall <- bind_rows(coxcvdhfh, coxhfh, coxcvd, coxdeath)

write.xlsx(coxall, paste0("./output/tabs/coxtab_sens_", Sys.Date(), ".xlsx"), rowNames = FALSE)

colnames(coxall) <- c("", rep(c(levels(pdata$htsens)), 3), "p-value interaction")
myHeader <- c(" " = 1, "HFrEF" = 3, "HFmrEF" = 3, "HFpEF" = 3, " " = 1)
names(myHeader) <- c(" ", "HFrEF", "HFmrEF", "HFpEF", " ")

footnote(mykable(coxall,
  fontsize = 10,
  caption = paste0("Associations between outcomes and HT by EF - Sensitivity analysis")
) %>%
  landscape() %>%
  add_header_above(myHeader),
symbol = c(
  "Incidence = no events, sum py, rate/1000py (95% CI)."
)
)
```
