```{r tab1, cache=cacheon}

# overall
tab1all <- print(CreateTableOne(
  vars = tabvars,
  data = pdata
),
missing = TRUE, printToggle = FALSE, nonnormal = tabvars,
catDigits = 0, contDigits = 0, pDigits = 3,
noSpaces = TRUE,
explain = FALSE
)
tab1all <- data.frame(tab1all) %>%
  rownames_to_column(var = "var") %>%
  select(var, Missing) %>%
  mutate(
    Missing = dF(as.numeric(Missing), 0),
    Missing = gsub("NA", "", Missing)
  )

# ref
tab1ref <- print(CreateTableOne(
  vars = tabvars,
  strata = "ht",
  data = pdata %>% filter(shf_ef_cat == "HFrEF")
),
missing = FALSE, printToggle = FALSE, nonnormal = tabvars,
test = TRUE,
catDigits = 0, contDigits = 0, pDigits = 3,
noSpaces = TRUE,
explain = FALSE
)
tab1ref <- data.frame(tab1ref) %>%
  rownames_to_column(var = "var") %>%
  select(var:p)

# mref
tab1mref <- print(CreateTableOne(
  vars = tabvars,
  strata = "ht",
  data = pdata %>% filter(shf_ef_cat == "HFmrEF")
),
missing = FALSE, printToggle = FALSE, nonnormal = tabvars,
test = TRUE,
catDigits = 0, contDigits = 0, pDigits = 3,
noSpaces = TRUE,
explain = FALSE
)
tab1mref <- data.frame(tab1mref) %>%
  rownames_to_column(var = "var") %>%
  select(var:p)

# pef
tab1pef <- print(CreateTableOne(
  vars = tabvars,
  strata = "ht",
  data = pdata %>% filter(shf_ef_cat == "HFpEF")
),
missing = FALSE, printToggle = FALSE, nonnormal = tabvars,
test = TRUE,
catDigits = 0, contDigits = 0, pDigits = 3,
noSpaces = TRUE,
explain = FALSE
)
tab1pef <- data.frame(tab1pef) %>%
  rownames_to_column(var = "var") %>%
  select(var:p)

tab1 <- Reduce(
  function(...) {
    full_join(...,
      by = "var"
    )
  },
  list(tab1all, tab1ref, tab1mref, tab1pef)
) %>%
  # remove = Yes
  mutate(across(everything(), str_replace_all, fixed(" = Yes"), "")) %>%
  # to get labs and units in place
  mutate(
    var_tmp = str_split(var, " = ", simplify = TRUE)[, 1],
    val_tmp = str_split(var, " = ", simplify = TRUE)[, 2],
    # if recoding or categorizing will still get org label
    var_tmp2 = str_replace_all(var_tmp, "(_cat2|_cat)", ""),
    # if shf/sos combination  will still get org label
    var_tmp2 = str_replace_all(var_tmp2, "shf_sos_com_", "sos_com_"),
  )

tab1 <- left_join(tab1,
  meta.variables.Sheet.1 %>%
    select(variable, label, unit),
  by = c("var_tmp2" = "variable")
) %>%
  mutate(
    Variable = coalesce(label, var_tmp),
    Variable = if_else(!is.na(unit),
      paste0(Variable, " (", unit, ")"),
      Variable
    ),
    Variable = if_else(val_tmp != "",
      paste0(Variable, " ", val_tmp),
      Variable
    )
  )


write.xlsx(tab1 %>%
  select(Variable, Missing:p), paste0("./output/tabs/tab1_", Sys.Date(), ".xlsx"), rowNames = FALSE)

# footnotes
tab1 <- tab1 %>%
  mutate(
    footnote1 = if_else(str_detect(var, "^shf_"), footnote_marker_symbol(1), ""),
    footnote2 = if_else(str_detect(var, "^sos_"), footnote_marker_symbol(2), ""),
    footnote3 = if_else(str_detect(var, "^ddr_"), footnote_marker_symbol(3), ""),
    footnote4 = if_else(str_detect(var, "^scb_"), footnote_marker_symbol(4), ""),
    footnote5 = if_else(var_tmp %in% modvars$var, footnote_marker_symbol(5), ""),
    footnote6 = if_else(str_detect(var, "^shf_rasarni"), footnote_marker_symbol(6), ""),
    footnote7 = if_else(str_detect(var, "^scb_dispincome_cat"), footnote_marker_symbol(7), "")
  ) %>%
  unite(footnote, starts_with("footnote"), sep = "") %>%
  mutate(
    # so no probs
    Variable = sanitizeTextFunc(Variable),

    Variable = paste0(Variable, footnote),

    # space in Latex output (fix this other way?)
    Variable = sub("  ", ". ", Variable)
  ) %>%
  select(Variable, Missing:p)


## fix in order to use escape = TRUE
colnames(tab1) <- sanitizeTextFunc(c(
  "Variables", "Missing (%)", rep(c(levels(pdata$ht), "p-value"), 3)
))


myHeader <- c(" " = 1, " " = 1, "HFrEF" = 4, "HFmrEF" = 4, "HFpEF" = 4)
names(myHeader) <- c(" ", " ", "HFrEF", "HFmrEF", "HFpEF")

footnote(
  mykable(tab1,
    fontsize = 3,
    caption = "Baseline characteristics",
    longtable = TRUE,
    escape = FALSE
  ) %>%
    landscape() %>%
    add_header_above(myHeader),
  general = c(
    "Categorical variables are presented with n (%) and tested with chi-square test and continuous variables with median [q1-q3] and tested with Kruskal-Wallis test."
  ),
  symbol = c(
    "Source: SwedeHF",
    "Source: NPR",
    "Source: DDR",
    "Source: SCB",
    "Included in the multiple imputation model (althought not necessarily imputed if there is no missing data) and logistic/cox models",
    "arb/acei/arni",
    "Medium within index year"
  )
)
```

```{r tab1afntprobnp, cache=cacheon}

# overall
tab1all <- print(CreateTableOne(
  vars = "shf_ntprobnp",
  data = pdata %>% filter(shf_sos_com_af == "Yes")
),
missing = TRUE, printToggle = FALSE, nonnormal = tabvars,
catDigits = 0, contDigits = 0, pDigits = 3,
noSpaces = TRUE,
explain = FALSE
)
tab1all <- data.frame(tab1all) %>%
  rownames_to_column(var = "var") %>%
  select(var, Missing) %>%
  mutate(
    Missing = dF(as.numeric(Missing), 0),
    Missing = gsub("NA", "", Missing)
  )

# ref
tab1ref <- print(CreateTableOne(
  vars = "shf_ntprobnp",
  strata = "ht",
  data = pdata %>% filter(shf_ef_cat == "HFrEF" & shf_sos_com_af == "Yes")
),
missing = FALSE, printToggle = FALSE, nonnormal = tabvars,
test = TRUE,
catDigits = 0, contDigits = 0, pDigits = 3,
noSpaces = TRUE,
explain = FALSE
)
tab1ref <- data.frame(tab1ref) %>%
  rownames_to_column(var = "var") %>%
  select(var:p)

# mref
tab1mref <- print(CreateTableOne(
  vars = "shf_ntprobnp",
  strata = "ht",
  data = pdata %>% filter(shf_ef_cat == "HFmrEF" & shf_sos_com_af == "Yes")
),
missing = FALSE, printToggle = FALSE, nonnormal = tabvars,
test = TRUE,
catDigits = 0, contDigits = 0, pDigits = 3,
noSpaces = TRUE,
explain = FALSE
)
tab1mref <- data.frame(tab1mref) %>%
  rownames_to_column(var = "var") %>%
  select(var:p)

# pef
tab1pef <- print(CreateTableOne(
  vars = "shf_ntprobnp",
  strata = "ht",
  data = pdata %>% filter(shf_ef_cat == "HFpEF" & shf_sos_com_af == "Yes")
),
missing = FALSE, printToggle = FALSE, nonnormal = tabvars,
test = TRUE,
catDigits = 0, contDigits = 0, pDigits = 3,
noSpaces = TRUE,
explain = FALSE
)
tab1pef <- data.frame(tab1pef) %>%
  rownames_to_column(var = "var") %>%
  select(var:p)

tab1 <- Reduce(
  function(...) {
    full_join(...,
      by = "var"
    )
  },
  list(tab1all, tab1ref, tab1mref, tab1pef)
) %>%
  # remove = Yes
  mutate(across(everything(), str_replace_all, fixed(" = Yes"), "")) %>%
  # to get labs and units in place
  mutate(
    # if shf/sos combination  will still get org label
    var_tmp2 = str_replace_all(var, "shf_sos_com_", "sos_com_"),
  )

tab1 <- left_join(tab1,
  meta.variables.Sheet.1 %>%
    select(variable, label, unit),
  by = c("var_tmp2" = "variable")
) %>%
  mutate(
    Variable = coalesce(label, var),
    Variable = if_else(!is.na(unit),
      paste0(Variable, " (", unit, ")"),
      Variable
    )
  )

tab1 <- tab1 %>%
  mutate(
    # so no probs
    Variable = sanitizeTextFunc(Variable),

    # space in Latex output (fix this other way?)
    Variable = sub("  ", ". ", Variable)
  ) %>%
  select(Variable, Missing:p)


## fix in order to use escape = TRUE
colnames(tab1) <- sanitizeTextFunc(c(
  "Variables", "Missing (%)", rep(c(levels(pdata$ht), "p-value"), 3)
))


myHeader <- c(" " = 1, " " = 1, "HFrEF" = 4, "HFmrEF" = 4, "HFpEF" = 4)
names(myHeader) <- c(" ", " ", "HFrEF", "HFmrEF", "HFpEF")

footnote(
  mykable(tab1,
    fontsize = 3,
    caption = "NT-proBNP for AF",
    escape = FALSE
  ) %>%
    landscape() %>%
    add_header_above(myHeader),
  general = c(
    "Categorical variables are presented with n (%) and tested with chi-square test and continuous variables with median [q1-q3] and tested with Kruskal-Wallis test."
  )
)
```

```{r tab1noafntprobnp, cache=cacheon}

# overall
tab1all <- print(CreateTableOne(
  vars = "shf_ntprobnp",
  data = pdata %>% filter(shf_sos_com_af == "No")
),
missing = TRUE, printToggle = FALSE, nonnormal = tabvars,
catDigits = 0, contDigits = 0, pDigits = 3,
noSpaces = TRUE,
explain = FALSE
)
tab1all <- data.frame(tab1all) %>%
  rownames_to_column(var = "var") %>%
  select(var, Missing) %>%
  mutate(
    Missing = dF(as.numeric(Missing), 0),
    Missing = gsub("NA", "", Missing)
  )

# ref
tab1ref <- print(CreateTableOne(
  vars = "shf_ntprobnp",
  strata = "ht",
  data = pdata %>% filter(shf_ef_cat == "HFrEF" & shf_sos_com_af == "No")
),
missing = FALSE, printToggle = FALSE, nonnormal = tabvars,
test = TRUE,
catDigits = 0, contDigits = 0, pDigits = 3,
noSpaces = TRUE,
explain = FALSE
)
tab1ref <- data.frame(tab1ref) %>%
  rownames_to_column(var = "var") %>%
  select(var:p)

# mref
tab1mref <- print(CreateTableOne(
  vars = "shf_ntprobnp",
  strata = "ht",
  data = pdata %>% filter(shf_ef_cat == "HFmrEF" & shf_sos_com_af == "No")
),
missing = FALSE, printToggle = FALSE, nonnormal = tabvars,
test = TRUE,
catDigits = 0, contDigits = 0, pDigits = 3,
noSpaces = TRUE,
explain = FALSE
)
tab1mref <- data.frame(tab1mref) %>%
  rownames_to_column(var = "var") %>%
  select(var:p)

# pef
tab1pef <- print(CreateTableOne(
  vars = "shf_ntprobnp",
  strata = "ht",
  data = pdata %>% filter(shf_ef_cat == "HFpEF" & shf_sos_com_af == "No")
),
missing = FALSE, printToggle = FALSE, nonnormal = tabvars,
test = TRUE,
catDigits = 0, contDigits = 0, pDigits = 3,
noSpaces = TRUE,
explain = FALSE
)
tab1pef <- data.frame(tab1pef) %>%
  rownames_to_column(var = "var") %>%
  select(var:p)

tab1 <- Reduce(
  function(...) {
    full_join(...,
      by = "var"
    )
  },
  list(tab1all, tab1ref, tab1mref, tab1pef)
) %>%
  # remove = Yes
  mutate(across(everything(), str_replace_all, fixed(" = Yes"), "")) %>%
  # to get labs and units in place
  mutate(
    # if shf/sos combination  will still get org label
    var_tmp2 = str_replace_all(var, "shf_sos_com_", "sos_com_"),
  )

tab1 <- left_join(tab1,
  meta.variables.Sheet.1 %>%
    select(variable, label, unit),
  by = c("var_tmp2" = "variable")
) %>%
  mutate(
    Variable = coalesce(label, var),
    Variable = if_else(!is.na(unit),
      paste0(Variable, " (", unit, ")"),
      Variable
    )
  )

# footnotes
tab1 <- tab1 %>%
  mutate(
    # so no probs
    Variable = sanitizeTextFunc(Variable),

    # space in Latex output (fix this other way?)
    Variable = sub("  ", ". ", Variable)
  ) %>%
  select(Variable, Missing:p)


## fix in order to use escape = TRUE
colnames(tab1) <- sanitizeTextFunc(c(
  "Variables", "Missing (%)", rep(c(levels(pdata$ht), "p-value"), 3)
))


myHeader <- c(" " = 1, " " = 1, "HFrEF" = 4, "HFmrEF" = 4, "HFpEF" = 4)
names(myHeader) <- c(" ", " ", "HFrEF", "HFmrEF", "HFpEF")

footnote(
  mykable(tab1,
    fontsize = 3,
    caption = "NT-proBNP for non-AF",
    escape = FALSE
  ) %>%
    landscape() %>%
    add_header_above(myHeader),
  general = c(
    "Categorical variables are presented with n (%) and tested with chi-square test and continuous variables with median [q1-q3] and tested with Kruskal-Wallis test."
  )
)
```
